version: '3.4'

services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite

  broooms.catalog.db:
    image: postgres:13-alpine

  broooms.cart.db:
    image: redis:6-alpine

  broooms.auth.db:
    image: mcr.microsoft.com/mssql/server:2019-latest

volumes:
  azurite_volume:
  catalog_db_volume:
  cart_db_volume:
  auth_db_volume:
