version: '3.4'

services:

  broooms.catalog.api:
    container_name: broooms_catalog_api
    depends_on:
      - broooms_catalog_db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "4101:80"
      - "4102:443"

  broooms.catalog.db:
    container_name: broooms_catalog_db
    restart: always
    ports:
      - 5101:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=catalog_db
    volumes:
      - /var/lib/postgresql/data
