version: '3.4'

services:
  azurite:
    container_name: azurite_dev
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - /data

  broooms.catalog.db:
    container_name: broooms_catalog_db
    restart: always
    ports:
      - 5101:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=catalog_db
    volumes:
      - /var/lib/postgresql/data
