version: '3.4'

services:
  azurite:
    container_name: azurite_dev
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - azurite_volume:/data

  broooms.catalog.db:
    container_name: broooms_catalog_db
    restart: always
    ports:
      - 5101:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=catalog_db
    volumes:
      - catalog_db_volume:/var/lib/postgresql/data

  broooms.cart.db:
    container_name: broooms_cart_db
    restart: always
    ports:
      - 5201:6379
    volumes:
      - cart_db_volume:/usr/local/etc/redis

  broooms.auth.db:
    container_name: broooms_auth_db
    restart: always
    ports:
      - 5301:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Docker123!
    volumes:
      - auth_db_volume:/var/opt/mssql
